apiVersion: v1
kind: Secret
metadata:
    labels:
      {{- include "chart-ide-igor.labels" . | nindent 4 }}
  {{- if .Values.secret.name }}           #se estiver definido use
  name: {{ .Values.secret.name }} 
  {{- else }}                             #senão estiver definido
  name: {{ include "chart-ide-igor.fullname" . }}
  {{- end }}
type: Opaque
{{- range $key, $val := .Values.secret.data }}     #percorre como lista
data:
  {{ $key }}: {{ $val | b64enc | quote }}          #coloca key:valor em > base64 > string
{{- end }}


